# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huarun', '0005_newsgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qianggou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('src', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=30)),
                ('smallimg1', models.CharField(max_length=100)),
                ('smallimg2', models.CharField(max_length=100)),
                ('smallimg3', models.CharField(max_length=100)),
                ('smallimg4', models.CharField(max_length=100)),
                ('smallimg5', models.CharField(max_length=100)),
                ('bigimg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('src', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=30)),
                ('smallimg1', models.CharField(max_length=100)),
                ('smallimg2', models.CharField(max_length=100)),
                ('smallimg3', models.CharField(max_length=100)),
                ('smallimg4', models.CharField(max_length=100)),
                ('smallimg5', models.CharField(max_length=100)),
                ('bigimg', models.CharField(max_length=100)),
            ],
        ),
    ]
