# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huarun', '0006_qianggou_topgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, unique=True)),
                ('phone', models.IntegerField(max_length=30)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
